databases:
  - name: imgurdb
    plan: free
    databaseName: imgurdb
    user: imgurdb_user

services:
  - type: web
    plan: free
    name: imgur
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn imgur.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: imgurdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
